# Generated by Django 3.1.4 on 2026-06-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeRentalApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
